project:
  type: website

website:
  title: "Statistical Computing Exercises"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: exercises/exercise-5.qmd
        text: Exercise 5

format:
  html:
    theme: cosmo
    toc: true
