project:
  type: website

website:
  title: "Statistical Computing Exercises"
  navbar:
    left:
      - href: index.qmd
        text: Home

      - text: Lessons
        menu:
          - href: lessons/lesson-6-visualization.qmd
            text: Visualization

      - text: Exercises
        menu:
          - href: exercises/exercise-5.qmd
            text: Exercise 5

format:
  html:
    theme: cosmo
    toc: true
