project:
  type: website

website:
  title: "Statistical Computing Exercises"
  navbar:
    left:
      - href: Exercise_5.qmd
        text: Exercise_5

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true